DEV-28242: add password requirements
acrolinx/platform-api pull request #105
Opened 2022-01-25 11:09 UTC by george-haddad

- Add password requirements to create user section
- Add version number of when new requirements start
- Add note that older version have different requirement
- Update error response to show the 2 different error responses for the 2 different versions
- Update error response in the Bulk Create request

2022-01-25 11:56 UTC, madeline-brennan commented on apiary.apib
> +As of Core Platform version 2022.02 password field is mandatory for creating a user.
```suggestion
As of Core Platform version 2022.02, the password field is required to create a user.
```

2022-01-25 11:56 UTC, madeline-brennan commented on apiary.apib
> +Below are the following password requirements:
```suggestion
Your password needs to meet the following requirements:
```

2022-01-25 12:03 UTC, tkrisztian95 reviewed
Looks good. Mainly recommendations for improvement.

2022-01-25 12:03 UTC, tkrisztian95 commented on apiary.apib
> +- Composed of ASCII printable characters
The requirements look accurate. 

I can only recommend that maybe some nested bullet points or merge and structure them like this could make it easier to read:

- Composed of ASCII printable characters only
- Must include at least
  - 1 lower case letter and 1 upper case letter [a-zA-Z]
  - 1 digit [0-9]
  - 1 special character symbol [& ,% ,@ , ...]
- Length must be between 10 to 64 characters long

2022-01-25 12:03 UTC, tkrisztian95 commented on apiary.apib
> +As of Core Platform version 2022.02 password field is mandatory for creating a user.
Please mention that the password requirements also be present during user update in the `### Update a User` section.

2022-01-25 12:13 UTC, tkrisztian95 commented on apiary.apib
> +- Composed of ASCII printable characters
Plus an example I think is favorable to showcase that `Secure_P@ssw0rd` is accepted (this string fulfills all the requirements). What do you think?

2022-01-25 12:39 UTC, madeline-brennan commented on apiary.apib
> +- Must be minimum 10 characters long
```suggestion
- Must be at least 10 characters long
```

2022-01-25 12:39 UTC, madeline-brennan commented on apiary.apib
> +- Must not exceed 64 characters long
```suggestion
- No more than 64 characters long
```

2022-01-25 12:39 UTC, madeline-brennan commented on apiary.apib
> +- Must include at least 1 lower case letter
```suggestion
- Needs to include at least 1 lower case letter
```

2022-01-25 12:40 UTC, madeline-brennan commented on apiary.apib
> +- Must include at least 1 upper case letter
```suggestion
- Needs to include at least 1 upper case letter
```

2022-01-25 12:40 UTC, madeline-brennan commented on apiary.apib
> +- Must include at least 1 digit
```suggestion
- Needs to include at least 1 digit
```

2022-01-25 12:40 UTC, madeline-brennan commented on apiary.apib
> +- Must include at least 1 special character symbol
```suggestion
- Needs to include at least 1 special character symbol
```

2022-01-25 12:41 UTC, madeline-brennan commented on apiary.apib
> +For Core Platform version 2021.05 up to 2022.02 the following apply:
```suggestion
For Core Platform versions 2021.05 to 2022.02, the following apply:
```

2022-01-25 12:41 UTC, madeline-brennan commented on apiary.apib
> +- Must be minimum of 1 character long
```suggestion
- At least 1 character long
```

2022-01-25 12:41 UTC, madeline-brennan commented on apiary.apib
> +- Must not exceed 128 characters
```suggestion
- No more than 128 characters
```

2022-01-25 12:45 UTC, madeline-brennan requested changes
Suggestions so far

2022-01-25 15:42 UTC, george-haddad commented on apiary.apib
> +- Composed of ASCII printable characters
I usually lean away from suggesting a secure password, just opens us up to issues if our suggestion is out of date or does not match their requirement. Another thing I avoid is to use examples of the allowed list of characters. For example the special symbols. I can't list it all (I mean I can but it will be ugly and long) It's literally all printable ASCII characters that exist in the ASCII table. But explaining it might be tough so using words that are familiar like "special characters" or "symbols" is easier. And then whatever works, works. And lastly, yes some structure would do good.

2022-01-25 16:09 UTC, george-haddad commented on apiary.apib
> +As of Core Platform version 2022.02 password field is mandatory for creating a user.
Please check commit https://github.com/acrolinx/platform-api/pull/105/commits/2b57b8c3b8c31851aa83696a83a222c9822a8192

2022-01-25 16:11 UTC, george-haddad commented on apiary.apib
> +Below are the following password requirements:
done.

2022-01-26 07:49 UTC, rbarbey approved these changes
Thanks for all the effort to make the requirements easily readable!

2022-01-26 08:01 UTC, madeline-brennan commented on apiary.apib
> +    - Updating the `password` field is available from Core Platform version 2022.02
```suggestion
    - You can update the `password` field as of Core Platform version 2022.02
```

2022-01-26 08:02 UTC, madeline-brennan approved these changes

2022-01-26 10:35 UTC, merged