Docs/dev 28893 privacy api
acrolinx/platform-api pull request #110
Opened 2022-02-11 09:23 UTC by mrnyax

2022-02-11 09:51 UTC, george-haddad requested changes
Please add the standard error responses if they omit the access token (401 response) and if calling it with out valid privileges (403 response). Also you need to add a note that they need `UserAndRoles.read` privileges to access the API.

2022-02-11 10:01 UTC, tkrisztian95 reviewed
Looks good.

2022-02-11 10:25 UTC, rbarbey requested changes

2022-02-11 10:25 UTC, rbarbey commented on apiary.apib
> +                "type": "privacySettingsIncompatible",
For completeness sake we might want to add this new error type to the list that on line 150.

2022-02-11 10:25 UTC, rbarbey commented on apiary.apib
> +- Scorecard privacy
I think I would add a note that setting `scorecardPrivacy` to `personal` and `anonymousChecking` to `true` is not possible and link to our official documentation maybe? @madeline-brennan what do you think?

2022-02-11 10:51 UTC, madeline-brennan commented on apiary.apib
> +- Scorecard privacy
I agree here, but would make sure to link to "Latest" so that docs changes don't break the link :)

2022-02-11 11:47 UTC, mrnyax commented on apiary.apib
> +                "type": "privacySettingsIncompatible",
I'll do a small Gitlab MR to fix this as well

2022-02-14 10:07 UTC, mrnyax commented on apiary.apib
> +- Scorecard privacy
@rbarbey and @madeline-brennan please review changes.

2022-02-14 10:13 UTC, madeline-brennan commented on apiary.apib
>  `queueLimitExceeded` | Queue limit exceeded | Retry to submit the check after waiting at least as long as suggested in the retry-after header.
```suggestion
`queueLimitExceeded` | Queue limit exceeded | You can resubmit the check after you wait at least as long as suggested in the retry-after header.
```

2022-02-14 10:14 UTC, madeline-brennan commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
Does this mean someone else is editing the data?

2022-02-14 10:21 UTC, madeline-brennan commented on apiary.apib
>  `licenseLimitExceeded` | License limit exceeded | You exceeded a limit set by your licensing terms. The error description contains more details. Please check [the documentation](https://docs.acrolinx
```suggestion
`licenseLimitExceeded` | License limit exceeded | You don't have anymore available licenses. Check the error description for more details. For more information about licensing, visit [the documentation](https://docs.acrolinx.com/coreplatform/latest/en/user-management/user-licenses).
```

2022-02-14 10:23 UTC, madeline-brennan commented on apiary.apib
> +This is an alternative way of getting information about the current (in request authorized) user.
```suggestion
This is an alternative way to get information about the user authorized in the request (current user).
```

2022-02-14 10:25 UTC, madeline-brennan commented on apiary.apib
> +In the Role API, Acrolinx defines a role as an entity that has an id, a name and list of privileges, and information on whether this role is a default role.
```suggestion
In the Role API, Acrolinx defines a role as an entity with an id, a name, and a list of privileges. It also tells you if the role is a default role.
```

2022-02-14 10:25 UTC, madeline-brennan commented on apiary.apib
> +- A valid access token and `Reporting.administration` privilege is required to access the APIs.
```suggestion
- To access the APIs, you'll need a valid access token and the `Reporting.administration` privilege.
```

2022-02-14 10:26 UTC, madeline-brennan commented on apiary.apib
> +- When `scorecardPrivacy` is set to `personal`, `anonymousChecking` can't be enabled. More information about scorecard privacy and anonymous checking can be found in the
```suggestion
- When `scorecardPrivacy` is set to `personal`, you can't enable `anonymousChecking`. You can find more information about scorecard privacy and anonymous checking in the
```

2022-02-14 10:28 UTC, madeline-brennan commented on apiary.apib
>  This request retrieves `scorecardPrivacy` and `anonymousChecking` values.
```suggestion
This request retrieves the values `scorecardPrivacy` and `anonymousChecking`.
```

2022-02-14 10:29 UTC, madeline-brennan commented on apiary.apib
> ++ Request Get privacy missing required privilege (application/json)
```suggestion
+ Request Get privacy when missing a required privilege (application/json)
```

2022-02-14 10:29 UTC, madeline-brennan commented on apiary.apib
> ++ Request Get privacy with invalid or missing access token (application/json)
```suggestion
+ Request Get privacy with an invalid or missing access token (application/json)
```

2022-02-14 10:30 UTC, madeline-brennan requested changes
Added some suggestions. Some of the text I changed might not apply to the current ticket, but fixed it if I saw it :)

2022-02-14 13:35 UTC, mrnyax commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
This seems to be the case. Maybe @rbarbey @george-haddad @tkrisztian95  can help us here.

2022-02-14 14:53 UTC, george-haddad approved these changes

2022-02-14 14:56 UTC, george-haddad commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
By definition concurrent write means data is being modified by more than 1 actor at a time. So I assume someone else is editing the data. But I am not 100% sure if it is another user or the same user but editing from a different place.

2022-02-14 15:54 UTC, madeline-brennan commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
@george-haddad, would something closer to "File/Data already in use" or "Locked for editing" be accurate here?

2022-02-15 08:09 UTC, george-haddad commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
@madeline-brennan very good question. I feel that "locked" is a good word to use. Although there is also the other part to retry with fresh data. Which got me a bit confused as it stipulates that the current data for the operation maybe be stale. I'll check with others who have their hands more into this area.

2022-02-15 10:54 UTC, george-haddad commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
@rbarbey what's your take on the wordings for the `conflict` error message. Usually this error rises when the backend cannot complete the request because there is something blocking it from doing so and returns to the user extra info that can help resolve this. One case would be what is currently written here about concurrent access ...etc. Though this may not be the case all the time, we send out 409 when there are duplicate records during a creation as well. So not sure if the list of error descriptions here is supposed to be generic or specific.

2022-02-21 14:29 UTC, rbarbey commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
I just had a look at the source code, this API error type is used only in a very specific situation when a document custom field is being changed by multiple people at once. But it could be reused for other APIs as well (for example if we were to redo our Terminology API, this situation could come up more often).

We rewrite this message to be less technical by saying something like: 

> Somebody else is changing the same data you're trying to change. Please be careful when trying to change it again at a later time.

At first I meant to write "don't start an edit war" but found the above second sentence to more … professional? 

But I would tackle this is a separate PR since this is unrelated to the Privacy API

2022-02-21 15:05 UTC, mrnyax commented on apiary.apib
>  `conflict` | Concurrent write access | Conflict with a concurrent write access. Retry the operation with fresh data.
I will proceed and resolve this conversation.

2022-03-30 11:27 UTC, closed without merging