DEV-28754 Query users with missing required custom fields
acrolinx/platform-api pull request #114
Opened 2022-03-15 10:27 UTC by tkrisztian95

Documents User API helper endpoint, provides a way to query users with missing required custom fields.

Add section ## Missing Required User Custom Fields
+ ### Count Users [HEAD /api/v1/user/custom-fields-missing]
+ ### Get Users [GET /api/v1/user/custom-fields-missing{?page,per_page}]

2022-03-15 10:48 UTC, george-haddad commented on apiary.apib
> +Returns the total number of users where one or more required user custom field has empty value.
Maybe this sounds better.

```suggestion
Returns the total number of users where one or more required user custom fields are empty.
```

2022-03-15 10:49 UTC, george-haddad commented on apiary.apib
> +- The users count will be returned as a header value in `X-Acrolinx-Total`.
```suggestion
- The users count will be returned as a value in the header `X-Acrolinx-Total`.
```

2022-03-15 12:43 UTC, madeline-brennan requested changes
Suggested edits

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +**What is a missing required custom field?** The user API representation returns the user related custom fields in the `customFields[]` array. In case there is a required custom field object (with `"
```suggestion
**What's a missing required custom field?** The User API returns your user-related custom fields in the `customFields[]` array. If a custom field is required (marked with `"inputType": "required"`) and is missing a value (`"value": ""`), the field is considered to be missing.
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +Returns the total number of users where one or more required user custom fields are empty.
```suggestion
Returns the total number of users who are missing one or more required user custom field.
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +- The users count will be returned as a value in the header `X-Acrolinx-Total`.
```suggestion
- You'll see the user count listed in the header `X-Acrolinx-Total`.
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +- It returns 0 (zero) when every user has some value provided for all required custom fields.
```suggestion
- It returns a 0 (zero) when no required custom fields are missing. 
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +    Query the number of users have missing custom field values in one or more required user custom fields.
```suggestion
    Query the number of users who are missing information in one or more required user custom fields.
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +Returns the filtered set of users where one or more required user custom field has empty value.
```suggestion
Returns a list of users who are missing one or more required user custom fields. 
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +**Note:** Similar to the User Resource > Get All Users request. It has pagination supported. See more details there.
```suggestion
**Note:** Similar to the User Resource > Get All Users request, it supports pagination. See more details there.
```
Do we want to link to the request?

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +You can query users with missing required custom fields.
```suggestion
You can query users who don't have required custom fields.
```

2022-03-15 12:43 UTC, madeline-brennan commented on apiary.apib
> +- The header value is a numeric type.
The user count is shown as a number.

2022-03-15 14:13 UTC, tkrisztian95 commented on apiary.apib
> +- The header value is a numeric type.
I'm considering this as important implementation-specific detail for the client.

2022-03-15 14:22 UTC, madeline-brennan commented on apiary.apib
> +- The header value is a numeric type.
In which case, would propose
- The user count will be shown in the header...
- The header value is a numeral.

2022-03-18 10:55 UTC, george-haddad commented on apiary.apib
> ++ Response 403 (application/json)
Are these error responses supposed to be empty or should they have the default error json response just like the ones in https://github.com/acrolinx/platform-api/blob/8a015696d9e1660c19bd1aaf203b3ef0035db0de/apiary.apib#L3921-L3943

2022-03-18 15:43 UTC, tkrisztian95 commented on apiary.apib
> ++ Response 403 (application/json)
Good question! These are not supposed to be empty, the linter shows warnings if a `HEAD` request returns with body regardless of success `2xx` or client/server-side error codes `4xx/5xx`. So, I simply removed the code block. I'll double-check but pretty sure the response won't be empty.

2022-03-21 08:17 UTC, george-haddad approved these changes

2022-03-21 08:21 UTC, madeline-brennan approved these changes

2022-03-21 08:22 UTC, merged