DEV-31765 acrolinxLive flag
acrolinx/platform-api pull request #121
Opened 2022-11-28 18:41 UTC by replrep

2022-12-14 12:23 UTC, rbarbey requested changes

2022-12-14 12:23 UTC, rbarbey commented on apiary.apib
> +If the server runs in Targets Mode, the guidance profiles contain an additional flag 'acrolinxLive'. This flag is true iff modern reuse is
I guess this new flag should be wrapped in backticks to show it as code in the docs?

```suggestion
If the server runs in Targets Mode, the guidance profiles contain an additional flag `acrolinxLive`. This flag is true iff modern reuse is
```

2022-12-14 12:23 UTC, rbarbey commented on apiary.apib
> +at least one reuse set configured.
Maybe it make this section more readable if all the conditions for this flag where part of a list? @madeline-brennan what do you think?

2022-12-16 14:12 UTC, madeline-brennan commented on apiary.apib
> +at least one reuse set configured.
Yes, I think so. I'd propose: 
```suggestion
If Targets mode is active, there is an additional flag called 'acrolinxLive'. This flag applies if the following is true:

- Modern Reuse is enabled on the server.
- The current user has the "Check documents" privilege.
- The selected Target contains the Approved Messaging goal with at least one Reuse set is configured.
```

2022-12-16 15:19 UTC, oliveoyl commented on apiary.apib
> +at least one reuse set configured.
I'd propose these typo tweaks.

```suggestion
If Targets mode is active, the response contains a flag called 'acrolinxLive'. This flag applies if the following 3 conditions are true:
- Reuse is enabled on the platform.
- The current user has the "Check documents" privilege.
- The selected Target contains the Approved Messaging goal with at least one Reuse set configured.```

2022-12-19 08:26 UTC, robertgrabowski commented
(Note: This PR is intentionally a draft - please don't merge until we review, change and extend the Acrolinx Live API in mid-2023.)

2024-01-03 15:59 UTC, hjohannsen commented
@replrep, I renamed the old `developer` branch to `develop` old and created a fresh `develop`-branch from `main`. Because the old branch kept causing weird merge issues. 

Please rebase the changes in this MR on the new `develop`-branch and direct your PR to _that_ branch.

Thanks and sorry for the inconvenience!

2024-07-31 10:08 UTC, closed without merging