docs: error response when external auth is enabled
acrolinx/platform-api pull request #126
Opened 2023-06-02 08:40 UTC by mrnyax

In this case, the external authentication system is used to manage password change

2023-06-02 09:40 UTC, hjohannsen approved these changes
Looks good to me.

2023-06-06 10:57 UTC, madeline-brennan commented on apiary.apib
> +                    "detail": "The user does not have the required privileges to perform the operation.",
```suggestion
                    "detail": "The user doesn't have the privileges required to perform the operation.",
```

2023-06-06 10:58 UTC, madeline-brennan commented on apiary.apib
> +                    "detail": "The user is not allowed to change password.",
```suggestion
                    "detail": "The user isn't allowed to change the password.",
```

2023-06-06 10:59 UTC, madeline-brennan requested changes
UX writer review

2023-06-06 10:59 UTC, madeline-brennan commented on apiary.apib
> +        // when external authentication is enable you should not be able to change password through the API
```suggestion
        // when external authentication is enabled, you shouldn't be able to change password through the API
```

2023-06-06 11:21 UTC, hjohannsen approved these changes

2023-06-08 07:36 UTC, madeline-brennan approved these changes

2023-06-08 07:37 UTC, madeline-brennan approved these changes

2023-06-08 08:35 UTC, merged