docs: Get all users include/exclude nested data
acrolinx/platform-api pull request #132
Opened 2023-10-06 07:00 UTC by tkrisztian95

2023-10-06 07:24 UTC, mrnyax approved these changes
Just some grammar changes. I think Madeline is an expert at this.

2023-10-06 07:24 UTC, mrnyax commented on apiary.apib
> +By default all custom field is returned nested in the user model.
```suggestion
By default all custom fields are returned nested in the user model.
```

2023-10-06 07:24 UTC, mrnyax commented on apiary.apib
> +Using the `includeCustomField` can help reduce the data transferred and fetch the only custom fields that are needed.
```suggestion
Using the `includeCustomField` can help reduce the data transferred and only fetch custom fields that are needed. 
```

2023-10-10 07:33 UTC, madeline-brennan requested changes

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +If you're managing a large number of users, you can benefit from the query params `includeCustomField` and `excludeProperties`.
```suggestion
If you manage a large number of users, you can use the query params `includeCustomField` and `excludeProperties` to filter nested data.
```

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +By default all custom fields are returned nested in the user model.
```suggestion
By default, all custom fields are nested in the user model.
```

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +Using the `includeCustomField` can help reduce the data transferred and only fetch custom fields that are needed.
```suggestion
You can use the parameter `includeCustomField` to limit the returned fields to those that match the key passed in the param value.
```

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +When specified, the custom fields returned are limited to those matching the key passed in the param value.
This is helpful if you want to fetch a specific set of custom fields to reduce data transfer.

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +To include more than one simply append N times the `&includeCustomField={Key}` to the request.
```suggestion
To include more than one custom field, add `&includeCustomField={Key}` to the request N times.
```

2023-10-10 07:33 UTC, madeline-brennan commented on apiary.apib
> +To include more than one simply append N times the `&includeCustomField={Key}` to the request.
I'm not clear if you have to reenter the parameter every time or if you just add another {Key}. Can you clarify? Also, should {Key} be upper or lower case? it looks like it's lower case in line 1345

2023-10-10 09:07 UTC, madeline-brennan commented on apiary.apib
>  When specified, the custom fields returned are limited to those matching the key passed in the param value.
```suggestion
This is helpful if you want to fetch a specific set of custom fields to reduce data transfer.
```

2023-10-10 09:10 UTC, tkrisztian95 commented on apiary.apib
> +To include more than one simply append N times the `&includeCustomField={Key}` to the request.
You need to append the whole `includeCustomField={Key}` with another key as query param. The {Key} should be replaced with value like "Department" its just a palecholder. 

For example `/api/v1/user?includeCustomField=Department&includeCustomField=Email&...`

2023-10-10 09:32 UTC, madeline-brennan approved these changes

2023-10-10 10:07 UTC, merged