feat: documentation for Reporting API
acrolinx/platform-api pull request #160
Opened 2024-08-26 15:01 UTC by Sonalit23

2024-08-28 10:51 UTC, madeline-brennan requested changes

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +The refill rate is 5 days of data per day. This way multiple entities or processes in the tenants org can mirror the data. The refill rate should also replenish the buffer over a longer time frame to
I'm not sure what you mean by "replenish the buffer" and "experimentation". Does the buffer refer to the amount of historical data available from today's date? What sort of experimentation are we assuming here?

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +The quota is applied per resource. For example downloads of check data won’t affect the quota for issues.
```suggestion
The quota is set for each type of data. For example, when you download check data it won't affect the amount of issue data you can download.
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +Quota violation will be indicated by a 429 status code. Appropriate Retry-After, RateLimit-Limit, RateLimit-Remaining, and RateLimit-Reset headers will be present on the response.
```suggestion
If you exceed the download quota, you'll get a 429 status code. The response will include the headers Retry-After, RateLimit-Limit, RateLimit-Remaining, and RateLimit-Reset headers.
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +Download checking data in CSV format
```suggestion
Download check data as a CSV file
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Check start time (string) - Start time of the check in the form `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, for example, `2022-08-01T23:49:14.627Z`
```suggestion
        + Check start time (string) - Start time of the check in the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, for example, `2022-08-01T23:49:14.627Z` 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Content reference (string) - Acrolinx assigns the file a content reference the first time you run a check. Files with the same content reference are treated as the same file
```suggestion
        + Content reference (string) - Acrolinx assigns the file a content reference the first time you run a check. Files with the same content reference are treated as the same file. 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +## Get checks data [GET /api/v1/reporting/data/checks?{start,end}]
```suggestion
## Get check data [GET /api/v1/reporting/data/checks?{start,end}]
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +    + start: `2024-08-23` (string, required) - downlaod data from this date
```suggestion
    + start: `2024-08-23` (string, required) - download data from this date
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Acrolinx score (number) - Overall Acrolinx Score
```suggestion
        + Acrolinx Score (number) - Overall Acrolinx Score 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Acrolinx Score color (string) - Color coding of the Acrolinx score
```suggestion
        + Acrolinx Score color (string) - Color coding of the Acrolinx Score 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Consistency score (number) - Score for the goal consistency
```suggestion
        + Goal Consistency score (number) - Score for the goal Consistency 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Correctness score (number) - Score for the goal correctness
```suggestion
        + Goal Correctness score (number) - Score for the goal Correctness 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Inclusive language score (number) - Score for the goal inclusive
```suggestion
        + Goal Inclusive Language score (number) - Score for the goal Inclusive Language 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Scannability score (number) - Score for the goal scannability
```suggestion
        + Goal Scannability score (number) - Score for the goal Scannability 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Terminology score (number) - Score for the goal terminology
```suggestion
        + Goal Terminology score (number) - Score for the goal Terminology 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Tone score (number) - Score for the goal tone
```suggestion
        + Goal Tone score (number) - Score for the goal Tone 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Words and Phrases score (number) -Score for the goal words and phrases
I think we decided to call this "terminology". Should we then have two instances of "Terminology"?

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Consistency issues (number) - Number of Issues found for the goal consistency
```suggestion
        + Goal Consistency issues (number) - Number of issues found for the goal Consistency 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Correctness issues (number) - Number of Issues found for the goal correctness
```suggestion
        + Goal Correctness issues (number) - Number of issues found for the goal Correctness 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Inclusive language issues  (number) - Number of Issues found for the goal inclusive
```suggestion
        + Goal Inclusive Language issues  (number) - Number of issues found for the goal Inclusive Language
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Scannability issues (number) - Number of Issues found for the goal scannability
```suggestion
        + Goal Scannability issues (number) - Number of issues found for the goal Scannability 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Terminology issues (number) - Number of Issues found for the goal terminology
```suggestion
        + Goal Terminology issues (number) - Number of issues found for the goal Terminology 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Goal Words and Phrases issues (number) - Number of issues found for the goal Words and Phrases
See comment above. Should we change this to "Terminology"? Not sure how the term change from "Words and Phrases" to "Terminology" should be handled since there's already a category called "Terminology" in the api

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Metric {NAME} (string) - Metrics suffix by actual name. If there are 10 Metrics then the CSV will have 10 coulms for metrics suffix by name of the metric
Can you explain this a bit more?

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +## Get Issues data [GET /api/v1/reporting/data/issues?{start,end}]
```suggestion
## Get issues data [GET /api/v1/reporting/data/issues?{start,end}]
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +Download issues found in documents in CSV format
```suggestion
Download issues found as a CSV file
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Date (string) - Date when the issue is found in the form `yyyy-MM-dd`, for example, `2022-01-20`
```suggestion
        + Date (string) - Date when the issue was found. Shown in the format `yyyy-MM-dd`, for example, `2022-01-20` 
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +        + Context (string) - Sentence or paragraph where the issue occurred.
```suggestion
        + Context (string) - Sentence or paragraph where the issue occurred
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Invalid 'end' date 2024-08-28. 'end' date must be before 2024-08-28, Data until yesterday can be downloaded."
```suggestion
            "message": "Invalid 'end' date 2024-08-28. 'end' date must be before 2024-08-28. The most recent data available for download is from yesterday."
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Unautherized access to reporting API, please contact admin/support."
```suggestion
            "message": "Unauthorized access to reporting API. Contact your Acrolinx administrator for help."
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "The Reporting API feature is disabled."
```suggestion
            "message": "The Reporting API feature is inactive."
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data before 2024-08-01 is available to download. Please change the dates if you would like to download the data until 2024-08-01."
```suggestion
            "message": "Data from before 2024-08-01 is available for download. If you would like to download the data up to 2024-08-01, adjust the dates."
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data is not available to download, please try again after sometime."
```suggestion
            "message": "Data is not available to download. Wait a few minutes and try again."
```

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
What specifically would trigger this?

2024-08-28 10:51 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Internal Server Error"
What specifically would trigger this?

2024-08-28 11:01 UTC, Sonalit23 commented on apiary.apib
> +The reporting API provides direct access to raw checks and issues data.
raw check data and raw issues data

2024-08-28 11:03 UTC, Sonalit23 commented on apiary.apib
> +The data is provided in a downloadable CSV format that further enables data analysis.
Yes end user must use some BI tools, excel or google sheets to do further data analysis. we are only providing raw (not aggregated) data.

2024-08-28 11:21 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data is not available to download, please try again after sometime."
I would not really suggest to wait for a few minutes because data scanning can take hours too. Can we rephrase this?

2024-08-28 11:23 UTC, Sonalit23 commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
Below restrictions:
**Concurrent Requests**
default: 3 requests per tenant
Since data downloads tend to take a long time in terms of HTTP requests, we limit the number of concurrent downloads per tenant. The default is 3 concurrent downloads.
Quota violation will be indicated by a 429 status code and a reason of Too many concurrent requests. Appropriate Retry-After, RateLimit-Limit, and RateLimit-Remaining headers will be present on the response.

**Download Volume**
default: 1000 days of data per tenant per resource (checks, issues…), replenishing at 5 days per day
The restriction of download volume is meant to encourage customers to use the Reporting API as a mechanism to transfer data into their own systems and then use these systems to analyze and access the data long term.
Any day of data downloaded, regardless of the amount of data contained, counts as a day of downloaded data. Even empty days. The big initial buffer is meant to allow experimentation and initial download of all available historic data.
The refill rate is 5 days of data per day. This way multiple entities or processes in the tenants org can mirror the data. The refill rate should also replenish the buffer over a longer time frame to allow new experimentation.

The quota is applied per resource. For example downloads of check data will not affect the quota for issues.

Quota violation will be indicated by a 429 status code. Appropriate Retry-After, RateLimit-Limit, RateLimit-Remaining, and RateLimit-Reset headers will be present on the response.

2024-08-28 11:23 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Internal Server Error"
Any technical exceptions or errors about which end user should not know.

2024-08-28 11:45 UTC, Sonalit23 commented on apiary.apib
> +        + Metric {NAME} (string) - Metrics suffix by actual name. If there are 10 Metrics then the CSV will have 10 coulms for metrics suffix by name of the metric
Examples:

- Informality metric score
- Liveliness metric score
- Readability metric score

The column name should be **actual name** followed by **metric score** same like goal score. I will correct the text.

2024-08-28 11:51 UTC, Sonalit23 commented on apiary.apib
> +        + Goal Words and Phrases issues (number) - Number of issues found for the goal Words and Phrases
The ticket is still open. we already have a separate goal with name 'Terminology'.

2024-08-29 10:23 UTC, Sonalit23 commented on apiary.apib
> +The data is provided in a downloadable CSV format that further enables data analysis.
If no changes required to this then shall we resolve the conversation?

2024-08-30 06:47 UTC, Sonalit23 commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
Or we can add two separate messages for the concurrent requests and volume exceeded?
I can make changes in code as per new messages.

I appreciate if you can suggest the messages for both Concurrent Requests and volume exceeded? so that I can make changes in both code and API docs. Thanks!

2024-08-30 06:48 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Internal Server Error"
I guess user can reach to Acrolinx support to report the issue. Additionally we can ask user to try again after sometime.

2024-08-30 09:36 UTC, madeline-brennan commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
@Sonalit23, great, will propose two messages. What does the user need to do if they see these messages? Do they just need to wait?

2024-08-30 09:49 UTC, Sonalit23 commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
yes

2024-08-30 14:29 UTC, Sonalit23 commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
No changes for Concurrent Requests message. Right?

2024-08-30 17:03 UTC, madeline-brennan commented on apiary.apib
> +            "message": "HTTP 429 Too Many Requests"
Ah! I thought I'd added those inline. Let me check

2024-09-02 07:08 UTC, madeline-brennan approved these changes

2024-09-02 07:17 UTC, madeline-brennan approved these changes

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Unautherized access to reporting API, please contact admin/support."
```suggestion
            "message": "Unauthorized access to reporting API. Contact your Acrolinx administrator for more information."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "The Reporting API feature is disabled."
```suggestion
            "message": "The Reporting API feature is inactive."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data before 2024-08-01 is available to download. Please change the dates if you would like to download the data until 2024-08-01."
```suggestion
            "message": "Data before 2024-08-01 is available to download. To download data up to 2024-08-01, adjust the dates."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
```suggestion
            "message": "No data is available for download. Try again later."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +        + Words and Phrases goal score (number) -Score for the goal words and phrases
```suggestion
        + Words and Phrases goal score (number) -Score for the goal Words and Phrases
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +        + {NAME} metric score (string) - Metrics suffix by actual name. If there are 10 Metrics then the CSV will have 10 coulms for metrics suffix by name of the metric
```suggestion
        + {NAME} metric score (string) - Metrics suffix by actual name. If there are 10 metrics, the CSV will have 10 columns for metrics suffix by name of the metric
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Invalid 'start' date 2024-08-29 and 'end' date 2024-08-28. 'start' date must be before 'end' date."
```suggestion
            "message": "Invalid 'start' date 2024-08-29 and 'end' date 2024-08-28. The 'start' date must be before the 'end' date."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Invalid 'end' date 2024-08-28. 'end' date must be before 2024-08-28. The most recent data available for download is from yesterday."
```suggestion
            "message": "Invalid 'end' date 2024-08-28. The 'end' date must be before 2024-08-28. The most recent data available for download is from yesterday."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Unauthorized access to reporting API. Contact your Acrolinx administrator for help."
```suggestion
            "message": "Unauthorized access to reporting API. Contact your Acrolinx administrator for more information."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data from before 2024-08-01 is available for download. If you would like to download the data up to 2024-08-01, adjust the dates."
```suggestion
            "message": "Data from before 2024-08-01 is available for download. To download the data up to 2024-08-01, change the dates."
```

2024-09-02 07:17 UTC, madeline-brennan commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
```suggestion
            "message": "Data isn't available to download. Try again later."
```

2024-09-02 07:17 UTC, madeline-brennan submitted a review, later dismissed

2024-09-02 07:56 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
we need to keep one of the version:
either 1. `No data is available for download. Try again later.` or 2. `Data isn't available to download. Try again later.`

2024-09-02 07:56 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
we need to keep one of the version:
either 1. No data is available for download. Try again later. or 2. Data isn't available to download. Try again later.

2024-09-02 07:57 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data before 2024-08-01 is available to download. Please change the dates if you would like to download the data until 2024-08-01."
we need to keep one of the version:
either `Data before 2024-08-01 is available to download. To download data up to 2024-08-01, adjust the dates.` or
`Data from before 2024-08-01 is available for download. To download the data up to 2024-08-01, change the dates.`

2024-09-02 07:57 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data from before 2024-08-01 is available for download. If you would like to download the data up to 2024-08-01, adjust the dates."
we need to keep one of the version:
either `Data before 2024-08-01 is available to download. To download data up to 2024-08-01, adjust the dates.` or
`Data from before 2024-08-01 is available for download. To download the data up to 2024-08-01, change the dates.`

2024-09-02 07:59 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data from before 2024-08-01 is available for download. If you would like to download the data up to 2024-08-01, adjust the dates."
final string - `Data before 2024-08-01 is available to download. To download data up to 2024-08-01, adjust the dates.`

2024-09-02 07:59 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
final string - No data is available for download. Try again later.

2024-09-02 07:59 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data is not available to download. Try again later."
final string - No data is available for download. Try again later.

2024-09-02 07:59 UTC, Sonalit23 commented on apiary.apib
> +            "message": "Data before 2024-08-01 is available to download. Please change the dates if you would like to download the data until 2024-08-01."
final string - Data before 2024-08-01 is available to download. To download data up to 2024-08-01, adjust the dates.

2024-09-02 08:08 UTC, madeline-brennan approved these changes

2024-09-02 08:08 UTC, merged