DEV-27221: User API pagination update
acrolinx/platform-api pull request #67
Opened 2021-08-24 13:47 UTC by george-haddad

- Add note about `prev` and `next` being omitted when those pages do not exist
- Add 400 response error when `per_page` exceeds max of 500 (or is not between 1 and 500)

2021-08-24 14:58 UTC, tkrisztian95 commented
I think this should target the `develop` branch instead.

2021-08-24 15:12 UTC, george-haddad commented
> I think this should target the `develop` branch instead.

Yeap, I think I just created this PR and it took `master` as the default.

2021-08-25 07:41 UTC, rbarbey requested changes
I think there's one addition needed (for the headers) but otherwise it looks good. Also thank you for removing the draft section at the bottom!

2021-08-25 07:41 UTC, rbarbey commented on apiary.apib
> +
I think we should also mention that the same applies to the next and prev page headers.

2021-08-25 07:48 UTC, george-haddad commented on apiary.apib
> +
Ah yes, true. I'll add that.

2021-08-25 08:33 UTC, rbarbey approved these changes
Thank you for the addition!

2021-08-25 08:35 UTC, merged