DEV-27630 Document User API endpoint(s) for request user(s) to update custom field value
acrolinx/platform-api pull request #86
Opened 2021-11-03 13:16 UTC by tkrisztian95

Add a call to the User API which allows requesting an update for users' custom fields. 

Note: This call requires the `UserAndRoles.editUser` privilege from the client.

+ Documented under the `User Commands` group
   + Added section for request `Request actualize Custom field values (single user)`
      + Example request and response

2021-11-05 13:11 UTC, george-haddad commented on apiary.apib
> +- When the user signs-in the next time the system will force him to re-enter the custom field values via a form.
better to change `him` to `them` keep things plural in order to be gender neutral

2021-11-05 13:12 UTC, george-haddad commented on apiary.apib
> +                "detail": "An unspecific client error occurred.",
Is this really the error message that is generated from a `404`? It sounds like a message for a `400` error

2021-11-05 13:13 UTC, george-haddad commented on apiary.apib
> +                "errors": []
It might be nice to include an example of an error here.

2021-11-08 08:33 UTC, tkrisztian95 commented on apiary.apib
> +- When the user signs-in the next time the system will force him to re-enter the custom field values via a form.
Sure. Thanks! :)

2021-11-08 08:49 UTC, tkrisztian95 commented on apiary.apib
> +                "detail": "An unspecific client error occurred.",
Yes, this is the message generated from a `404`. I can agree.

2021-11-08 09:12 UTC, tkrisztian95 commented on apiary.apib
> +                "detail": "An unspecific client error occurred.",
I've started a discussion about possible improvements here.

2021-11-08 09:23 UTC, tkrisztian95 commented on apiary.apib
> +                "errors": []
I'll add some. Thanks!

2021-11-08 09:34 UTC, tkrisztian95 commented on apiary.apib
> +                "errors": []
Added an extra request example with the invalid user ids to showcase the errors. See the changes here: b59fb6d

2021-11-09 09:04 UTC, george-haddad approved these changes
Looks cool to me, nice example on the request with invalid ids

2021-11-09 09:16 UTC, rbarbey reviewed
I just had some nitpicky comments, feel free to ignore them.

2021-11-09 09:16 UTC, rbarbey commented on apiary.apib
> +The user specified by the *id* in this request will be notified to actualize his custom field values.
To be in line with our own style guide, I think we should use "their" instead of "his" but I'm not absolutely sure. @madeline-brennan is that correct?

2021-11-09 09:16 UTC, rbarbey commented on apiary.apib
> +- If you repeat the request with a user id who had been request earlier, you won't see an error.
I would uppercase id here but that's a matter of taste I guess.

2021-11-09 09:16 UTC, rbarbey commented on apiary.apib
> ++ Request Request one User to actualize his custom field values
Same as above: "their" instead of "his".

2021-11-09 09:51 UTC, tkrisztian95 commented on apiary.apib
> +- If you repeat the request with a user id who had been request earlier, you won't see an error.
I'll change it to uppercase "ID", thanks!

2021-11-09 10:20 UTC, tkrisztian95 commented on apiary.apib
> ++ Request Request one User to actualize his custom field values
Fixed in: 9bb9f26

2021-11-09 10:20 UTC, tkrisztian95 commented on apiary.apib
> +- If you repeat the request with a user id who had been request earlier, you won't see an error.
Fixed in: 9bb9f26

2021-11-09 10:21 UTC, tkrisztian95 commented on apiary.apib
> +The user specified by the *id* in this request will be notified to actualize his custom field values.
Updated in: 9bb9f26

2021-11-09 10:34 UTC, madeline-brennan commented on apiary.apib
> +The user specified by the *id* in this request will be notified to actualize his custom field values.
Yes, definitely

2021-11-09 11:20 UTC, madeline-brennan commented on apiary.apib
> +### Request actualize Custom field values  [PUT /api/v1/user/{id}/_request_cf_update]
```suggestion
### Request User Information Update  [PUT /api/v1/user/{id}/_request_cf_update]
```

2021-11-09 11:37 UTC, madeline-brennan requested changes
Made some updates to the text for clarity/to reflect how we talk about this in other places.

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +The user specified by the *id* in this request will be notified to actualize their custom field values.
```suggestion
The user specified by the *id* in this request will be asked to update their user information. 
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +- When the user signs-in the next time the system will force them to re-enter the custom field values via a form.
```suggestion
- The next time the user signs in, they'll need to re-enter their user information via a form.
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> ++ Request Request one User to actualize their custom field values
```suggestion
+ Request Ask one user to update their user information
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +### Request actualize Custom field values in Bulk  [PUT /api/v1/user/bulk/_request_cf_update]
```suggestion
### Request Bulk User Information Update  [PUT /api/v1/user/bulk/_request_cf_update]
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +### Request actualize Custom field values  [PUT /api/v1/user/{id}/_request_cf_update]
In the UI we just refer to this as an "Information Update" because "Custom" is used in a few different scenarios nd can get a little tricky.

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +This API is the bulk variant of the same "Request actualize Custom field values" from the User Commands group.
```suggestion
This API is the bulk operation for "Request User Information Update" from the "User Commands" group.
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +This API is the bulk variant of the same "Request actualize Custom field values" from the User Commands group.
We call these "Bulk Operations" in line 3580

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +It lets you request multiple users to actialize their custom field values.
```suggestion
It lets you ask multiple users to update their user information. 
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +**Note:** Currently there is no limitations in terms of the maximal users a client could request for update.
```suggestion
**Note:** There are currently no limitations on the number of users a client can ask for an information update.
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> ++ Request Request multiple Users to actualize their Custom field values (application/json)
```suggestion
+ Request Ask multiple users to update their user information (application/json)
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
```suggestion
+ Request If user ids in the request are invalid or unknown (application/json)
```

2021-11-09 11:37 UTC, madeline-brennan commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
Does this mean that you won't be notified if you've submitted a request twice?

2021-11-09 11:53 UTC, tkrisztian95 commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
I'm a bit hesitant about this change, I would prefer to have an indicator like `Example ...` in the request name (the part after the `+ Request`) about this is just an error example request. What do you think?

2021-11-09 11:54 UTC, tkrisztian95 commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
Yes, it does. You can submit the request and repeat it multiple times. The client won't be notified about the user already requested for the information update.

2021-11-09 11:57 UTC, madeline-brennan commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
Ok, in that case I'll make a small adjustment

2021-11-09 12:00 UTC, madeline-brennan commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
```suggestion
- If you repeat the request for the same user UUID, you won't be notified that you've already submitted a request. 
```

2021-11-09 12:03 UTC, madeline-brennan commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
```suggestion
- If you repeat the request for the same user UUID, you won't be notified that a request was already submitted. 
```

2021-11-09 12:04 UTC, tkrisztian95 commented on apiary.apib
> +- If you repeat the request with the same user UUID, you won't see an error.
Thanks!

2021-11-09 12:04 UTC, madeline-brennan commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
I see what you mean. In this caase, we can leave it as is.

2021-11-09 12:09 UTC, tkrisztian95 commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
I can also think about changing this `Errors Example - If user ids in the request are invalid or unknown` which would look like this:
![image](https://user-images.githubusercontent.com/8113120/140921720-d3020c27-370a-499a-bf01-3cfb514c3568.png)

How about this?

2021-11-09 12:12 UTC, tkrisztian95 commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
@george-haddad Please also take a look. 

I think in this way we could add multiple `Errors Example - If something ...` invalid client type request samples to showcase the error handling and possible error results.

2021-11-09 12:32 UTC, madeline-brennan commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
@tkrisztian95, this works from my perspective. However, I'd make it singular: "Error Example" or "Example Error"

2021-11-09 12:57 UTC, tkrisztian95 commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
Sounds good! Thanks @madeline-brennan

2021-11-09 13:19 UTC, madeline-brennan approved these changes

2021-11-09 13:27 UTC, george-haddad commented on apiary.apib
> ++ Request Example with invalid or unknown user ids in request (application/json)
This conversation was resolved before I had a chance to look at it, do you still need me to take a look?

2021-11-09 15:42 UTC, merged