DEV-27677 I can delete users in bulk
acrolinx/platform-api pull request #87
Opened 2021-11-09 09:04 UTC by mrnyax

- Add API to delete users in bulk

2021-11-09 09:07 UTC, george-haddad commented on apiary.apib
> +                ],
Check the indentation here. It looks like the stuff inside the `{  }` should be indented 1 level in.

2021-11-09 09:12 UTC, mrnyax commented on apiary.apib
> +                ],
Fixed it.

2021-11-09 10:18 UTC, tkrisztian95 commented on apiary.apib
> +                    "status": 204,
I think these result fields between the `{  ...  }` should be tabulated a bit more right.

2021-11-09 10:18 UTC, tkrisztian95 commented on apiary.apib
> +            // when 4 users were deleted successfully but 1 wasn’t
I think this comment is not in sync with the provided example response. I would expect `4` items in the `results` array and only `1` in the `errors`

2021-11-09 10:18 UTC, tkrisztian95 commented on apiary.apib
> +                    "detail": "size must be between 1 and 2",
I think, you should use here the original `size must be between 1 and 100` text and simply change the value of `"invalidValue"` to something like 
` "invalidValue": "[d6601a5b-c74e-4753-8d7a-4a7d15e71149, d7b6d898-79b2-4a8b-9afd-760fdda9c921, ...",`. I mean like using the `...` dots to indicate there are more items expected there.

2021-11-09 10:18 UTC, tkrisztian95 commented on apiary.apib
> +                    "location": null
I think this field should be omitted from the serialization in the case of containing `null` value. 
I remember I've done it in my MR recently. 

Could you please check if the API is really returning the `location` filed with the `null` value?

2021-11-09 10:18 UTC, tkrisztian95 commented on apiary.apib
> +    This request lets you delete 5 users by specifying user uuids in the request object.
I think here we should also use uppercase `UUIDs` instead.

2021-11-09 10:27 UTC, mrnyax commented on apiary.apib
> +                    "status": 204,
That's right. Thanks for spotting that

2021-11-09 10:27 UTC, mrnyax commented on apiary.apib
> +                    "status": 204,
That's right. Thanks for spotting that

2021-11-09 10:33 UTC, mrnyax commented on apiary.apib
> +            // when 4 users were deleted successfully but 1 wasn’t
Updated the description to match response

2021-11-09 10:46 UTC, george-haddad reviewed
Some comments

2021-11-09 10:50 UTC, mrnyax commented on apiary.apib
> +                    "location": null
Indeed they are not on the response.

2021-11-09 13:25 UTC, madeline-brennan commented on apiary.apib
> +noted in the Delete User API section.
```suggestion
noted in the "Delete User API" section.
```

2021-11-09 13:28 UTC, madeline-brennan requested changes
Just a couple of small tweaks

2021-11-09 13:28 UTC, madeline-brennan commented on apiary.apib
> ++ Request Delete Users in Bulk (application/json)
```suggestion
+ Request Delete users in bulk (application/json)
```

2021-11-10 08:28 UTC, tkrisztian95 commented on apiary.apib
> +            // when 2 users were deleted successfully but 3 weren't
Could you please move this response to a separate error example request?

2021-11-10 08:34 UTC, madeline-brennan approved these changes

2021-11-10 09:09 UTC, tkrisztian95 commented on apiary.apib
> ++ Request when 2 users were deleted successfully but 3 weren't (application/json)
Naming recommendation: 
```suggestion
+ Request Example with users cannot delete (application/json)
```

2021-11-10 09:09 UTC, tkrisztian95 commented on apiary.apib
> +            // when all users were successfully delete
I think this comment can be also removed from here.
```suggestion

```

2021-11-10 10:01 UTC, george-haddad approved these changes

2021-11-10 10:49 UTC, george-haddad commented on apiary.apib
> ++ Request Example with users cannot delete (application/json)
It should be something like 
```suggestion
+ Request Example with users that cannot be deleted (application/json)
```

2021-11-10 10:50 UTC, george-haddad reviewed
Found this one change

2021-11-10 10:50 UTC, madeline-brennan commented on apiary.apib
> ++ Request Example with users cannot delete (application/json)
Would use "can't" instead of cannot

2021-11-10 10:53 UTC, george-haddad commented on apiary.apib
> ++ Request Example with users cannot delete (application/json)
I updated the suggestion change, thanks.

2021-11-10 11:01 UTC, merged