DEV-27807 Allow correct sorting by license status if the user has the license type Named user
acrolinx/platform-api pull request #88
Opened 2021-11-15 13:15 UTC by mrnyax

The user api needs to provide the possibility to sort the license type column also by status

2021-11-15 14:02 UTC, tkrisztian95 commented on apiary.apib
> +- Query parameter `licenseType` sorts by two fields `licenseType` and `licenseStatus`
I think a dot is missing from the end of this sentence:
```suggestion
- Query parameter `licenseType` sorts by two fields `licenseType` and `licenseStatus`.
```

2021-11-15 14:42 UTC, madeline-brennan commented on apiary.apib
> +- Query parameter `licenseType` sorts by two fields `licenseType` and `licenseStatus`.
```suggestion
- Query parameter `licenseType` sorts by two fields: `licenseType` and `licenseStatus`.
```

2021-11-15 14:43 UTC, madeline-brennan requested changes
Just a small tweak

2021-11-16 07:55 UTC, tkrisztian95 approved these changes
Looks good. Thanks!

2021-11-16 07:56 UTC, tkrisztian95 approved these changes

2021-11-16 07:58 UTC, madeline-brennan approved these changes

2021-11-16 12:57 UTC, george-haddad approved these changes
:+1:

2021-11-16 12:57 UTC, merged