term API doc: added referenced ACTIF sample file
acrolinx/platform-api pull request #89
Opened 2021-11-15 16:43 UTC by robertgrabowski

* Terminology API documentation is referencing a sample ACTIF term file in the "create term entries" section
* this ACTIF file is now added (to the `doc/` subfolder)

2021-11-18 08:08 UTC, tkrisztian95 reviewed
Looks good! Thanks for adding this example.

PS: I'm a bit hesitant about adding the example file to the `/doc` directory. Maybe a dedicated folder for such files like `/examples` could be an alternative.

2021-11-18 08:09 UTC, tkrisztian95 approved these changes

2021-11-18 12:19 UTC, madeline-brennan commented on term-api.md
>  - If the input data contains more than one entry (which is allowed), all will be created or updated respectively, but
What is "all" referring to here? All entries?

2021-11-18 12:20 UTC, madeline-brennan reviewed
Question that will influence edits

2021-11-18 13:01 UTC, robertgrabowski commented on term-api.md
>  - If the input data contains more than one entry (which is allowed), all will be created or updated respectively, but
all = all entries in the input data. I clarified this in another commit.

2021-11-18 13:18 UTC, madeline-brennan commented on term-api.md
>    the Location header will only contain the URL of one of them.
```suggestion
  the "Location" header will only contain the URL of one of them.
```

2021-11-18 13:19 UTC, madeline-brennan commented on term-api.md
>  - If no new entry was created or updated but it’s no error (for example, the input data could be empty and not contain any
the "but it's no error" part of this is confusing to me

2021-11-22 14:06 UTC, robertgrabowski commented on term-api.md
>  - If no new entry was created or updated but it’s no error (for example, the input data could be empty and not contain any
I shortened it.

2021-11-22 14:06 UTC, robertgrabowski commented on term-api.md
>    the Location header will only contain the URL of one of them.
Changed.

2021-11-22 14:49 UTC, madeline-brennan commented on term-api.md
> +- If the input data does not contain entry to create or update, the return code is 204 (No Content).
```suggestion
- If the input data doesn't contain an entry that needs to be created or updated, you'll see a 204 (no content).
```

2021-11-22 14:50 UTC, madeline-brennan commented on term-api.md
> +- If the input data contains more than one entry (which is allowed), all entries in the input data will be created or updated respectively, but
```suggestion
- If the input data contains more than one entry (which is allowed), all entries in the input data will be created or updated respectively. However,
```

2021-11-22 14:51 UTC, madeline-brennan commented on term-api.md
>  - In both cases, creation or update, the return code of the service is 201 (Created) and the Location header gets the
```suggestion
- For both creation and update, the return code is 201 (created) and the "Location" header gets the
```

2021-11-22 14:52 UTC, madeline-brennan requested changes
Final suggestions for clarity/style

2021-11-23 14:00 UTC, robertgrabowski commented
@madeline-brennan I applied all your final style suggestions, but I asked you for a re-review, because I think you still need to approve the PR so that it can be merged.

2021-11-23 14:09 UTC, madeline-brennan approved these changes
Looks good

2021-11-24 08:30 UTC, merged