docs: add example for sort by licenceType
acrolinx/platform-api pull request #91
Opened 2021-11-18 12:42 UTC by mrnyax

2021-11-18 12:52 UTC, george-haddad commented on apiary.apib
> +
To keep the responses short and consistent with all the other responses in the document, let's keep the results to 4 total users. I feel for seeing sorted users it should be enough.

Using built-in users is a nice touch because it is realistic and something the customer will see. Instead of using names like Admin1 and Admin2, we're using at most 2 consistent pre-defined users in the document (usernames `fred` and `franz`). Take a look at this lines https://github.com/acrolinx/platform-api/blob/develop/apiary.apib#L1430-L1500 you can use 2 built in users and these 2 already existing users in the response.

2021-11-19 08:02 UTC, george-haddad commented on apiary.apib
> +                        "licenseType": "named",
Please change this to the other existing user we are using whose username is "franz"

2021-11-19 08:26 UTC, mrnyax commented on apiary.apib
> +                        "licenseType": "named",
Forgot this one. Thanks

2021-11-19 08:41 UTC, george-haddad commented on apiary.apib
> ++ Request Get a list of all users sort ascending by licenseType (application/json)
I think this can be reworded like

```suggestion
+ Request Get a list of all users sorted by license type in ascending order (application/json)
```

2021-11-19 08:43 UTC, george-haddad commented on apiary.apib
> ++ Request Get a list of all users sort descending by licenseType (application/json)
I don't think we need to add both examples of the sort in `ASC` and `DSC`. I believe that showing 1 example is good enough and the user is probably knowledgeable enough to know there is 2 sorting orders.

2021-11-19 09:32 UTC, george-haddad commented on apiary.apib
> +                        "licenseType": "named",
It still is different than the ones being used in the file. Please look at the JSON objects here https://github.com/acrolinx/platform-api/blob/develop/apiary.apib#L1429-L1500 and notices the properties are different. They should be the same, not just the name and username, but the roles and all the other fields.

2021-11-19 10:36 UTC, george-haddad requested changes
One more change, the request showing the sort is for some reason under the `### Get a User (Self) [GET /api/v1/user/self]` section. Maybe a mistake because the file is so large. Should be moved to the `### Get All Users [GET /api/v1/user{?sort,page,per_page}]`

Aside from that on ordering, things look good.

2021-11-19 10:47 UTC, madeline-brennan approved these changes

2021-11-19 12:49 UTC, mrnyax commented
> One more change, the request showing the sort is for some reason under the `### Get a User (Self) [GET /api/v1/user/self]` section. Maybe a mistake because the file is so large. Should be moved to the `### Get All Users [GET /api/v1/user{?sort,page,per_page}]`
> 
> Aside from that on ordering, things look good.

Fixed this.

2021-11-22 08:19 UTC, george-haddad approved these changes

2021-11-22 08:21 UTC, merged