docs: add fullName and username search params
acrolinx/platform-api pull request #96
Opened 2021-12-08 09:10 UTC by mrnyax

2021-12-08 09:48 UTC, tkrisztian95 commented on apiary.apib
> +    + fullName (string, optional) - Optional query parameter for searching by fullName
```suggestion
    + fullName (string, optional) - Optional query parameter for searching by full name
```

2021-12-08 09:48 UTC, tkrisztian95 commented on apiary.apib
> +### Get All Users [GET /api/v1/user{?sort,page,per_page,fullName,username}]
I would suggest to have the `username` param appended first:
```suggestion
### Get All Users [GET /api/v1/user{?sort,page,per_page,username,fullName}]
```

2021-12-13 05:44 UTC, tkrisztian95 commented on apiary.apib
I would create a `Search` or `Filtering` paragraph with a short description and add these notes. What do you think? 

PS: Currently, this is in the `Sorting` section's notes.

2021-12-30 09:12 UTC, rbarbey requested changes

2021-12-30 09:12 UTC, rbarbey commented on apiary.apib
> +
I would add that if both parameters set then users are found that have the given `username` or the given `fullName` but not both (OR and not AND)

2021-12-30 09:36 UTC, rbarbey approved these changes

2021-12-30 09:36 UTC, merged