DEV-27981 Sorting of one column will sort by username within the selected column
acrolinx/platform-api pull request #99
Opened 2022-01-06 09:24 UTC by mrnyax

This PR updates the documentation on sorting. The sort results are additionally sorted by `username` field if not the sort parameter value.

2022-01-06 09:36 UTC, george-haddad commented on apiary.apib
> +- The list is additionally sorted by `username` if sort value isn't `username`.
This line might sound confusing to most persons, and I must admit it's not easy to word. I will give it a try

`The sorted result is additionally sorted by 'username', the exception is when the primary sort column is 'username' to begin with`

Maybe @madeline-brennan might have a better way to word it.

2022-01-06 09:51 UTC, mrnyax commented on apiary.apib
> +- The list is additionally sorted by `username` if sort value isn't `username`.
I agree. Add @madeline-brennan as a reviewer

2022-01-06 10:24 UTC, madeline-brennan requested changes

2022-01-06 10:24 UTC, madeline-brennan commented on apiary.apib
> +- The list is additionally sorted by `username` if sort value isn't `username`.
How about:
```suggestion
- The list is also sorted by `username` unless this is already the primary sort column.
```

2022-01-07 10:15 UTC, madeline-brennan approved these changes

2022-01-07 10:17 UTC, george-haddad approved these changes

2022-01-07 10:17 UTC, merged